# TSLhead 头颅插件配置文件
# 配置不同类型的头颅模板

# 核心管理层级
SSR:
  name: "&#FFD700&l✧ &#FFD700[SSR]&#FFFF00 ༺{Player_name}༻ &#FFD700&l✧"
  lore:
    - "&e▰▰▰ 服务器中枢 ▰▰▰"
    - "&6✦ 最高决策权限持有者"
    - "&e「拥有以下专属特权」"
    - "&7- 修改世界基础规则"
    - "&7- 实时查看服务器日志"
    - "&7- 发起紧急维护指令"
    - "&8┃ &e⚙️ 核心控制台 &8┃"

# 特殊贡献层级
SR:
  name: "&#BA55D3&l❈ &d[SR]&5 ༺{Player_name}༻ &#BA55D3&l❈"
  lore:
    - "&d▣▣▣ 特殊贡献 ▣▣▣"
    - "&5✦ 身份类型：&f特殊贡献者"
    - "&5✦ 贡献履历：&f多项重大任务"
    - "&d「已解锁特权」"
    - "&7- 定制专属宣传展位"
    - "&7- 审核通道优先通行"
    - "&8┃ &d📜 贡献者勋章 &8┃"

# 基础贡献层级
R:
  name: "&#1E90FF&l✦ &3[R]&b ༺{Player_name}༻ &#1E90FF&l✦"
  lore:
    - "&b▢▢▢ 中流砥柱 ▢▢▢"
    - "&3⏳ 累计服务时长：&b充足"
    - "&3📊 服务稳定性评级：&b优秀"
    - "&b「基础权益」"
    - "&7- 双倍周常奖励"
    - "&7- 专属客服通道"
    - "&8┃ &3🛡️ 守护者契约 &8┃"

# 基础成员层级
N:
  name: " &7[N] &f {Player_name} ♥"
  lore:
    - "&#aaf6c0  ▩▩▩ TSLの新生力量 ▩▩▩"
    - "&#d0ffde「这颗头颅见证了{Player_name}在服务器世界中走过的一百小时」"
    - "&#d0ffde「愿它永远守护你在TSLの回忆」"
    - "&8 ┃ &7描述在头颅放置后会消失哦 &8┃"

SHOP:
  name: "&#1E90FF&l✦ &3[？]&b{Player_name} &#1E90FF&l✦"
  lore:
    - ""
    - "&bTSL喵在腐竹卧室找到的"
    - ""
    - "&3有使用过的痕迹 ♥"
    - ""
    - "&8 ┃ &7描述在头颅放置后会消失哦 &8┃"

# 示例头颅配置
example:
  name: "&6{Player_name} &7的头颅"
  lore:
    - "&7这是 &6{Player_name} &7的头颅"
    - "&8右键点击查看详情"

# 纪念头颅配置
memorial:
  name: "&#aaf6c0&l{Player_name} &7♥"
  lore:
    - "&#aaf6c0▩▩▩ TSL的新生力量 ▩▩▩"
    - "&#d0ffde「这颗头颅见证了{Player_name}在服务器世界中的足迹」"
    - "&#d0ffde「愿它永远守护你在TSL的回忆」"
    - "&8 ┃ &7描述在头颅放置后会消失哦 &8┃"

# VIP头颅配置
vip:
  name: "&b&l[VIP] &f{Player_name}"
  lore:
    - "&b✦ VIP专属头颅 ✦"
    - "&7玩家: &f{Player_name}"
    - "&8限量收藏版"

# 管理员头颅配置
admin:
  name: "&c&l[ADMIN] &4{Player_name}"
  lore:
    - "&c⚡ 管理员专属头颅 ⚡"
    - "&7玩家: &f{Player_name}"
    - "&4权威象征"
